name: CI/CD Pipeline for Ranking Model App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .

  lint-format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .
      - name: Lint with flake8
        run: |
          flake8 main/
      #- name: Check formatting with black
      #  run: |
      #    black --check main/

  tests:
    runs-on: ubuntu-latest
    needs: lint-format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .
      - name: Run unit tests with coverage
        run: |
          pytest -n auto --cov=main --cov-report=xml --cov-report=term --cov-fail-under=1 -m "unit" tests/
      - name: Run performance tests
        run: |
          pytest -m "performance" tests/
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

  app-health:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .
      - name: Start app server
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5
      - name: Health check - Ping app
        run: |
          curl --fail http://localhost:8000/health
