name: CI Pipeline for Ranking Model App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-poetry-deps.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python and Poetry
        uses: ./.github/actions/setup-python-poetry

      - name: Cache Poetry dependencies
        id: cache-poetry-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-

      - name: Install dependencies
        if: steps.cache-poetry-deps.outputs.cache-hit != 'true'
        run: poetry install --no-interaction

  lint-format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python and Poetry
        uses: ./.github/actions/setup-python-poetry

      - name: Lint with flake8
        run: poetry run flake8 main/

      # Uncomment if you want Black formatting check too
      # - name: Check formatting with black
      #   run: poetry run black --check main/

  tests:
    runs-on: ubuntu-latest
    needs: lint-format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python and Poetry
        uses: ./.github/actions/setup-python-poetry

      - name: Train model
        run: poetry run python -m main.train

      - name: Run unit tests with coverage
        run: poetry run pytest --cov=main --cov-report=xml --cov-report=term --cov-fail-under=1 -m "unit" tests/

      - name: Run performance tests
        run: poetry run pytest -m "performance" tests/

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

  app-health:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python and Poetry
        uses: ./.github/actions/setup-python-poetry

      - name: Start app server
        run: |
          poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Health check - Ping app
        run: curl --fail http://localhost:8000/

  security-check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python and Poetry
        uses: ./.github/actions/setup-python-poetry

      - name: Run Bandit (Security linter)
        run: poetry run bandit -r main/ -ll

      - name: Run Safety (Dependency vulnerability checker)
        run: poetry run safety check
